FROM jzmatrix/baseimage:debian10_apache24_php74_finance_openidc_20220624_1529
################################################################################
RUN apt update && \
    apt -y upgrade 
################################################################################
ADD www /var/www/html
RUN chmod -R 755 /var/www/html/*
################################################################################
CMD [ "/opt/startServices.sh" ]
