apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      hostNetwork: false
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        name: {{ .Values.serviceName }}
        env:
          - name: siteURL
            value: "{{- .Values.serviceURL }}"
        envFrom:
        - secretRef:
            name: db-config
        - secretRef:
            name: oidc-config
        imagePullPolicy: Always
        ports:
        - containerPort: 80